//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMate.Weather.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WeatherResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WeatherResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniMate.Weather.Resources.WeatherResources", typeof(WeatherResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klar.
        /// </summary>
        internal static string Weather_Clear {
            get {
                return ResourceManager.GetString("Weather_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewölkt.
        /// </summary>
        internal static string Weather_Cloudy {
            get {
                return ResourceManager.GetString("Weather_Cloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebel.
        /// </summary>
        internal static string Weather_Fog {
            get {
                return ResourceManager.GetString("Weather_Fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starker Nieselregen.
        /// </summary>
        internal static string Weather_HeavyDrizzle {
            get {
                return ResourceManager.GetString("Weather_HeavyDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starker gefrierender Nieselregen.
        /// </summary>
        internal static string Weather_HeavyFreezingDrizzle {
            get {
                return ResourceManager.GetString("Weather_HeavyFreezingDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starker gefrierender Regen.
        /// </summary>
        internal static string Weather_HeavyFreezingRain {
            get {
                return ResourceManager.GetString("Weather_HeavyFreezingRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starker Regen.
        /// </summary>
        internal static string Weather_HeavyRain {
            get {
                return ResourceManager.GetString("Weather_HeavyRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starke Regenschauer.
        /// </summary>
        internal static string Weather_HeavyRainShowers {
            get {
                return ResourceManager.GetString("Weather_HeavyRainShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starker Schneefall.
        /// </summary>
        internal static string Weather_HeavySnowfall {
            get {
                return ResourceManager.GetString("Weather_HeavySnowfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starke Schneeschauer.
        /// </summary>
        internal static string Weather_HeavySnowShowers {
            get {
                return ResourceManager.GetString("Weather_HeavySnowShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichter Nieselregen.
        /// </summary>
        internal static string Weather_LightDrizzle {
            get {
                return ResourceManager.GetString("Weather_LightDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichter gefrierender Nieselregen.
        /// </summary>
        internal static string Weather_LightFreezingDrizzle {
            get {
                return ResourceManager.GetString("Weather_LightFreezingDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichter gefrierender Regen.
        /// </summary>
        internal static string Weather_LightFreezingRain {
            get {
                return ResourceManager.GetString("Weather_LightFreezingRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichter Regen.
        /// </summary>
        internal static string Weather_LightRain {
            get {
                return ResourceManager.GetString("Weather_LightRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichte Regenschauer.
        /// </summary>
        internal static string Weather_LightRainShowers {
            get {
                return ResourceManager.GetString("Weather_LightRainShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichter Schneefall.
        /// </summary>
        internal static string Weather_LightSnowfall {
            get {
                return ResourceManager.GetString("Weather_LightSnowfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichte Schneeschauer.
        /// </summary>
        internal static string Weather_LightSnowShowers {
            get {
                return ResourceManager.GetString("Weather_LightSnowShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überwiegend klar.
        /// </summary>
        internal static string Weather_MainlyClear {
            get {
                return ResourceManager.GetString("Weather_MainlyClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mässiger Nieselregen.
        /// </summary>
        internal static string Weather_ModerateDrizzle {
            get {
                return ResourceManager.GetString("Weather_ModerateDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mässiger Regen.
        /// </summary>
        internal static string Weather_ModerateRain {
            get {
                return ResourceManager.GetString("Weather_ModerateRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mässige Regenschauer.
        /// </summary>
        internal static string Weather_ModerateRainShowers {
            get {
                return ResourceManager.GetString("Weather_ModerateRainShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mässiger Schneefall.
        /// </summary>
        internal static string Weather_ModerateSnowfall {
            get {
                return ResourceManager.GetString("Weather_ModerateSnowfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilweise bewölkt.
        /// </summary>
        internal static string Weather_PartlyCloudy {
            get {
                return ResourceManager.GetString("Weather_PartlyCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reifnebel.
        /// </summary>
        internal static string Weather_RimeFog {
            get {
                return ResourceManager.GetString("Weather_RimeFog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schneekörner.
        /// </summary>
        internal static string Weather_SnowGrains {
            get {
                return ResourceManager.GetString("Weather_SnowGrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewitter.
        /// </summary>
        internal static string Weather_Thunderstorm {
            get {
                return ResourceManager.GetString("Weather_Thunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewitter mit starkem Hagel.
        /// </summary>
        internal static string Weather_ThunderstormHeavyHail {
            get {
                return ResourceManager.GetString("Weather_ThunderstormHeavyHail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewitter mit leichtem Hagel.
        /// </summary>
        internal static string Weather_ThunderstormLightHail {
            get {
                return ResourceManager.GetString("Weather_ThunderstormLightHail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        internal static string Weather_Unknown {
            get {
                return ResourceManager.GetString("Weather_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string Wind_E {
            get {
                return ResourceManager.GetString("Wind_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONO.
        /// </summary>
        internal static string Wind_ENE {
            get {
                return ResourceManager.GetString("Wind_ENE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSO.
        /// </summary>
        internal static string Wind_ESE {
            get {
                return ResourceManager.GetString("Wind_ESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string Wind_N {
            get {
                return ResourceManager.GetString("Wind_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string Wind_NE {
            get {
                return ResourceManager.GetString("Wind_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNO.
        /// </summary>
        internal static string Wind_NNE {
            get {
                return ResourceManager.GetString("Wind_NNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNW.
        /// </summary>
        internal static string Wind_NNW {
            get {
                return ResourceManager.GetString("Wind_NNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        internal static string Wind_NW {
            get {
                return ResourceManager.GetString("Wind_NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Wind_S {
            get {
                return ResourceManager.GetString("Wind_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO.
        /// </summary>
        internal static string Wind_SE {
            get {
                return ResourceManager.GetString("Wind_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSO.
        /// </summary>
        internal static string Wind_SSE {
            get {
                return ResourceManager.GetString("Wind_SSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSW.
        /// </summary>
        internal static string Wind_SSW {
            get {
                return ResourceManager.GetString("Wind_SSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        internal static string Wind_SW {
            get {
                return ResourceManager.GetString("Wind_SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string Wind_W {
            get {
                return ResourceManager.GetString("Wind_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WNW.
        /// </summary>
        internal static string Wind_WNW {
            get {
                return ResourceManager.GetString("Wind_WNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSW.
        /// </summary>
        internal static string Wind_WSW {
            get {
                return ResourceManager.GetString("Wind_WSW", resourceCulture);
            }
        }
    }
}
