//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMate.Modules.Location.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocationResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniMate.Modules.Location.Resources.LocationResources", typeof(LocationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ort suchen (z.B. Zürich, Bern, Basel...).
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wird geladen....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 📍 Mein Standort.
        /// </summary>
        public static string MyLocation {
            get {
                return ResourceManager.GetString("MyLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mein Standort.
        /// </summary>
        public static string MyLocationText {
            get {
                return ResourceManager.GetString("MyLocationText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ihr Standort konnte nicht ermittelt werden. Bitte überprüfen Sie Ihre Browser-Einstellungen und versuchen Sie es erneut..
        /// </summary>
        public static string GeolocationError {
            get {
                return ResourceManager.GetString("GeolocationError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Standortzugriff wurde verweigert. Bitte erlauben Sie den Zugriff in Ihren Browser-Einstellungen..
        /// </summary>
        public static string GeolocationPermissionDenied {
            get {
                return ResourceManager.GetString("GeolocationPermissionDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Standort ist nicht verfügbar. Bitte überprüfen Sie Ihre Internetverbindung oder GPS-Einstellungen..
        /// </summary>
        public static string GeolocationUnavailable {
            get {
                return ResourceManager.GetString("GeolocationUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ℹ️ Ungefährer Standort basierend auf Ihrer IP-Adresse. Die Genauigkeit beträgt ca. 10-50 km..
        /// </summary>
        public static string LocationApproximate {
            get {
                return ResourceManager.GetString("LocationApproximate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Standort.
        /// </summary>
        public static string UnknownLocation {
            get {
                return ResourceManager.GetString("UnknownLocation", resourceCulture);
            }
        }
    }
}
