//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniMate.Modules.Weather.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WeatherResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public WeatherResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiniMate.Modules.Weather.Resources.WeatherResources", typeof(WeatherResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewölkung.
        /// </summary>
        public static string CloudCover {
            get {
                return ResourceManager.GetString("CloudCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌤️ Aktuelles Wetter.
        /// </summary>
        public static string CurrentWeather {
            get {
                return ResourceManager.GetString("CurrentWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wetterdaten konnten nicht geladen werden. Bitte versuchen Sie es später erneut..
        /// </summary>
        public static string ErrorLoadingWeatherData {
            get {
                return ResourceManager.GetString("ErrorLoadingWeatherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden der Wetterdaten: {0}.
        /// </summary>
        public static string ErrorLoadingWeatherDataWithMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingWeatherDataWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standort konnte nicht ermittelt werden. Bitte erlauben Sie den Standortzugriff oder suchen Sie manuell nach einem Ort..
        /// </summary>
        public static string ErrorMessageWeatherLocation {
            get {
                return ResourceManager.GetString("ErrorMessageWeatherLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefühlt {0}.
        /// </summary>
        public static string FeelsLike {
            get {
                return ResourceManager.GetString("FeelsLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 24-Stunden Vorhersage.
        /// </summary>
        public static string Forecast_24HourTitle {
            get {
                return ResourceManager.GetString("Forecast_24HourTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden der Vorhersage: {0}.
        /// </summary>
        public static string Forecast_ErrorLoading {
            get {
                return ResourceManager.GetString("Forecast_ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Vorhersagedaten....
        /// </summary>
        public static string Forecast_LoadingData {
            get {
                return ResourceManager.GetString("Forecast_LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Regen:.
        /// </summary>
        public static string Forecast_MaxRain {
            get {
                return ResourceManager.GetString("Forecast_MaxRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Max:.
        /// </summary>
        public static string Forecast_MinMax {
            get {
                return ResourceManager.GetString("Forecast_MinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Vorhersagedaten verfügbar..
        /// </summary>
        public static string Forecast_NoDataAvailable {
            get {
                return ResourceManager.GetString("Forecast_NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenintensität.
        /// </summary>
        public static string Forecast_RainIntensity {
            get {
                return ResourceManager.GetString("Forecast_RainIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Standort konnte nicht ermittelt werden. Bitte überprüfen Sie Ihre Browser-Einstellungen und versuchen Sie es erneut..
        /// </summary>
        public static string GeolocationError {
            get {
                return ResourceManager.GetString("GeolocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standortzugriff wurde verweigert. Bitte erlauben Sie den Zugriff in Ihren Browser-Einstellungen..
        /// </summary>
        public static string GeolocationPermissionDenied {
            get {
                return ResourceManager.GetString("GeolocationPermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitüberschreitung beim Ermitteln Ihres Standorts. Bitte stellen Sie sicher, dass GPS aktiviert ist und versuchen Sie es erneut..
        /// </summary>
        public static string GeolocationTimeout {
            get {
                return ResourceManager.GetString("GeolocationTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standortbestimmung nicht verfügbar. Desktop-PCs haben normalerweise kein GPS. Bitte nutzen Sie die Suchfunktion, um Ihren Ort einzugeben..
        /// </summary>
        public static string GeolocationTimeoutDesktop {
            get {
                return ResourceManager.GetString("GeolocationTimeoutDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standort ist nicht verfügbar. Bitte überprüfen Sie Ihre Internetverbindung oder GPS-Einstellungen..
        /// </summary>
        public static string GeolocationUnavailable {
            get {
                return ResourceManager.GetString("GeolocationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luftfeuchtigkeit.
        /// </summary>
        public static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Aktualisierung: {0}.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wird geladen....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wetterdaten werden geladen....
        /// </summary>
        public static string LoadingWeatherData {
            get {
                return ResourceManager.GetString("LoadingWeatherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standort.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ️ Ungefährer Standort basierend auf Ihrer IP-Adresse. Die Genauigkeit beträgt ca. 10-50 km..
        /// </summary>
        public static string LocationApproximate {
            get {
                return ResourceManager.GetString("LocationApproximate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📍 Mein Standort.
        /// </summary>
        public static string MyLocation {
            get {
                return ResourceManager.GetString("MyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Standort.
        /// </summary>
        public static string MyLocationText {
            get {
                return ResourceManager.GetString("MyLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wetter.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niederschlag.
        /// </summary>
        public static string Precipitation {
            get {
                return ResourceManager.GetString("Precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luftdruck.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regen.
        /// </summary>
        public static string Rain {
            get {
                return ResourceManager.GetString("Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erneut versuchen.
        /// </summary>
        public static string RetryButton {
            get {
                return ResourceManager.GetString("RetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort suchen (z.B. Zürich, Bern, Basel...).
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herbst.
        /// </summary>
        public static string Season_Autumn {
            get {
                return ResourceManager.GetString("Season_Autumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frühling.
        /// </summary>
        public static string Season_Spring {
            get {
                return ResourceManager.GetString("Season_Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sommer.
        /// </summary>
        public static string Season_Summer {
            get {
                return ResourceManager.GetString("Season_Summer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string Season_Winter {
            get {
                return ResourceManager.GetString("Season_Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schneefall.
        /// </summary>
        public static string Snowfall {
            get {
                return ResourceManager.GetString("Snowfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Standort.
        /// </summary>
        public static string UnknownLocation {
            get {
                return ResourceManager.GetString("UnknownLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UV-Index.
        /// </summary>
        public static string UVIndex {
            get {
                return ResourceManager.GetString("UVIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichtweite.
        /// </summary>
        public static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klar.
        /// </summary>
        public static string Weather_Clear {
            get {
                return ResourceManager.GetString("Weather_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewölkt.
        /// </summary>
        public static string Weather_Cloudy {
            get {
                return ResourceManager.GetString("Weather_Cloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebel.
        /// </summary>
        public static string Weather_Fog {
            get {
                return ResourceManager.GetString("Weather_Fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starker Nieselregen.
        /// </summary>
        public static string Weather_HeavyDrizzle {
            get {
                return ResourceManager.GetString("Weather_HeavyDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starker gefrierender Nieselregen.
        /// </summary>
        public static string Weather_HeavyFreezingDrizzle {
            get {
                return ResourceManager.GetString("Weather_HeavyFreezingDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starker gefrierender Regen.
        /// </summary>
        public static string Weather_HeavyFreezingRain {
            get {
                return ResourceManager.GetString("Weather_HeavyFreezingRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starker Regen.
        /// </summary>
        public static string Weather_HeavyRain {
            get {
                return ResourceManager.GetString("Weather_HeavyRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starke Regenschauer.
        /// </summary>
        public static string Weather_HeavyRainShowers {
            get {
                return ResourceManager.GetString("Weather_HeavyRainShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starker Schneefall.
        /// </summary>
        public static string Weather_HeavySnowfall {
            get {
                return ResourceManager.GetString("Weather_HeavySnowfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starke Schneeschauer.
        /// </summary>
        public static string Weather_HeavySnowShowers {
            get {
                return ResourceManager.GetString("Weather_HeavySnowShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichter Nieselregen.
        /// </summary>
        public static string Weather_LightDrizzle {
            get {
                return ResourceManager.GetString("Weather_LightDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichter gefrierender Nieselregen.
        /// </summary>
        public static string Weather_LightFreezingDrizzle {
            get {
                return ResourceManager.GetString("Weather_LightFreezingDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichter gefrierender Regen.
        /// </summary>
        public static string Weather_LightFreezingRain {
            get {
                return ResourceManager.GetString("Weather_LightFreezingRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichter Regen.
        /// </summary>
        public static string Weather_LightRain {
            get {
                return ResourceManager.GetString("Weather_LightRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichte Regenschauer.
        /// </summary>
        public static string Weather_LightRainShowers {
            get {
                return ResourceManager.GetString("Weather_LightRainShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichter Schneefall.
        /// </summary>
        public static string Weather_LightSnowfall {
            get {
                return ResourceManager.GetString("Weather_LightSnowfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leichte Schneeschauer.
        /// </summary>
        public static string Weather_LightSnowShowers {
            get {
                return ResourceManager.GetString("Weather_LightSnowShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überwiegend klar.
        /// </summary>
        public static string Weather_MainlyClear {
            get {
                return ResourceManager.GetString("Weather_MainlyClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mässiger Nieselregen.
        /// </summary>
        public static string Weather_ModerateDrizzle {
            get {
                return ResourceManager.GetString("Weather_ModerateDrizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mässiger Regen.
        /// </summary>
        public static string Weather_ModerateRain {
            get {
                return ResourceManager.GetString("Weather_ModerateRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mässige Regenschauer.
        /// </summary>
        public static string Weather_ModerateRainShowers {
            get {
                return ResourceManager.GetString("Weather_ModerateRainShowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mässiger Schneefall.
        /// </summary>
        public static string Weather_ModerateSnowfall {
            get {
                return ResourceManager.GetString("Weather_ModerateSnowfall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teilweise bewölkt.
        /// </summary>
        public static string Weather_PartlyCloudy {
            get {
                return ResourceManager.GetString("Weather_PartlyCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reifnebel.
        /// </summary>
        public static string Weather_RimeFog {
            get {
                return ResourceManager.GetString("Weather_RimeFog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schneekörner.
        /// </summary>
        public static string Weather_SnowGrains {
            get {
                return ResourceManager.GetString("Weather_SnowGrains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewitter.
        /// </summary>
        public static string Weather_Thunderstorm {
            get {
                return ResourceManager.GetString("Weather_Thunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewitter mit starkem Hagel.
        /// </summary>
        public static string Weather_ThunderstormHeavyHail {
            get {
                return ResourceManager.GetString("Weather_ThunderstormHeavyHail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewitter mit leichtem Hagel.
        /// </summary>
        public static string Weather_ThunderstormLightHail {
            get {
                return ResourceManager.GetString("Weather_ThunderstormLightHail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        public static string Weather_Unknown {
            get {
                return ResourceManager.GetString("Weather_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese App zeigt nur allgemeine Wetterinformationen. Wetterwarnungen werden nicht angezeigt. Bei wichtigen Wetterlagen frag bitte deine Eltern oder schaut zusammen in die offiziellen Wetterwarnungen..
        /// </summary>
        public static string WeatherWarningNotice {
            get {
                return ResourceManager.GetString("WeatherWarningNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 7-Tage Vorhersage.
        /// </summary>
        public static string WeeklyForecast_7DayTitle {
            get {
                return ResourceManager.GetString("WeeklyForecast_7DayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Laden der Wochenvorhersage: {0}.
        /// </summary>
        public static string WeeklyForecast_ErrorLoading {
            get {
                return ResourceManager.GetString("WeeklyForecast_ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Wochenvorhersage....
        /// </summary>
        public static string WeeklyForecast_LoadingData {
            get {
                return ResourceManager.GetString("WeeklyForecast_LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Wochenvorhersage verfügbar..
        /// </summary>
        public static string WeeklyForecast_NoDataAvailable {
            get {
                return ResourceManager.GetString("WeeklyForecast_NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        public static string Wind_E {
            get {
                return ResourceManager.GetString("Wind_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONO.
        /// </summary>
        public static string Wind_ENE {
            get {
                return ResourceManager.GetString("Wind_ENE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSO.
        /// </summary>
        public static string Wind_ESE {
            get {
                return ResourceManager.GetString("Wind_ESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string Wind_N {
            get {
                return ResourceManager.GetString("Wind_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string Wind_NE {
            get {
                return ResourceManager.GetString("Wind_NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNO.
        /// </summary>
        public static string Wind_NNE {
            get {
                return ResourceManager.GetString("Wind_NNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NNW.
        /// </summary>
        public static string Wind_NNW {
            get {
                return ResourceManager.GetString("Wind_NNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        public static string Wind_NW {
            get {
                return ResourceManager.GetString("Wind_NW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string Wind_S {
            get {
                return ResourceManager.GetString("Wind_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SO.
        /// </summary>
        public static string Wind_SE {
            get {
                return ResourceManager.GetString("Wind_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSO.
        /// </summary>
        public static string Wind_SSE {
            get {
                return ResourceManager.GetString("Wind_SSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSW.
        /// </summary>
        public static string Wind_SSW {
            get {
                return ResourceManager.GetString("Wind_SSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        public static string Wind_SW {
            get {
                return ResourceManager.GetString("Wind_SW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string Wind_W {
            get {
                return ResourceManager.GetString("Wind_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WNW.
        /// </summary>
        public static string Wind_WNW {
            get {
                return ResourceManager.GetString("Wind_WNW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSW.
        /// </summary>
        public static string Wind_WSW {
            get {
                return ResourceManager.GetString("Wind_WSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windböen.
        /// </summary>
        public static string WindGusts {
            get {
                return ResourceManager.GetString("WindGusts", resourceCulture);
            }
        }
    }
}
